import { useMemo, useCallback } from "react";
import { Copy, FileCode } from "lucide-react";
import { showToast } from "../ui/Toast";
import type { BlockProject } from "../../lib/types";

interface Props {
  project: BlockProject;
}

function toPascalCase(s: string): string {
  return s
    .split(/[-_ ]/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join("");
}

function generateBlockPreview(block: BlockProject): string {
  const className = toPascalCase(block.name);
  const packageName = `com.${block.mod_id}`;
  const extends_ = block.has_block_entity ? "BlockWithEntity" : "Block";

  let code = `package ${packageName}.block;\n\n`;
  code += `import net.alloymc.api.block.Block;\n`;
  code += `import net.alloymc.api.block.BlockProperties;\n`;
  code += `import net.alloymc.api.block.BlockState;\n`;
  code += `import net.alloymc.api.registry.Registry;\n`;

  if (block.has_block_entity) {
    code += `import net.alloymc.api.block.BlockWithEntity;\n`;
    code += `import net.alloymc.api.block.entity.BlockEntity;\n`;
    code += `import net.alloymc.api.util.BlockPos;\n`;
  }
  if (block.has_gui) {
    code += `import net.alloymc.api.player.Player;\n`;
    code += `import net.alloymc.api.util.Hand;\n`;
    code += `import net.alloymc.api.util.ActionResult;\n`;
    code += `import net.alloymc.api.util.HitResult;\n`;
  }

  code += `\n/**\n * ${block.display_name}\n * Generated by Alloy IDE Block Editor\n */\n`;
  code += `public class ${className} extends ${extends_} {\n\n`;
  code += `    public ${className}() {\n`;
  code += `        super(BlockProperties.of()\n`;
  code += `            .strength(${block.properties.hardness}f, ${block.properties.resistance}f)\n`;

  if (block.properties.requires_tool) {
    code += `            .requiresTool()\n`;
  }
  if (block.properties.light_level > 0) {
    code += `            .luminance(state -> ${block.properties.light_level})\n`;
  }
  if (block.properties.is_transparent) {
    code += `            .nonOpaque()\n`;
  }
  if (block.properties.has_gravity) {
    code += `            .gravity()\n`;
  }
  if (Math.abs(block.properties.slipperiness - 0.6) > 0.001) {
    code += `            .slipperiness(${block.properties.slipperiness}f)\n`;
  }

  code += `        );\n    }\n`;

  if (block.has_block_entity) {
    code += `\n    @Override\n`;
    code += `    public BlockEntity createBlockEntity(BlockPos pos, BlockState state) {\n`;
    code += `        return new ${className}BlockEntity(pos, state);\n`;
    code += `    }\n`;
  }

  if (block.has_gui) {
    code += `\n    @Override\n`;
    code += `    public ActionResult onUse(BlockState state, Player player, Hand hand, HitResult hit) {\n`;
    code += `        if (!player.getWorld().isClient()) {\n`;
    code += `            BlockEntity be = player.getWorld().getBlockEntity(hit.getBlockPos());\n`;
    code += `            if (be instanceof ${className}BlockEntity) {\n`;
    code += `                player.openScreen((${className}BlockEntity) be);\n`;
    code += `            }\n`;
    code += `        }\n`;
    code += `        return ActionResult.SUCCESS;\n`;
    code += `    }\n`;
  }

  code += `}\n`;
  return code;
}

function generateRegistrationSnippet(block: BlockProject): string {
  const className = toPascalCase(block.name);
  const upper = block.name.toUpperCase();

  return `// Register block: ${className}
public static final Block ${upper} = Registry.register(
    Blocks.class,
    "${block.name}",
    new ${className}()
);

// Register block item
public static final Item ${upper}_ITEM = Registry.register(
    Items.class,
    "${block.name}",
    new BlockItem(${upper}, new ItemProperties())
);`;
}

export default function BlockCodePreview({ project }: Props) {
  const code = useMemo(() => generateBlockPreview(project), [project]);
  const snippet = useMemo(() => generateRegistrationSnippet(project), [project]);

  const copyCode = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(code);
      showToast("success", "Copied to clipboard");
    } catch {
      showToast("error", "Failed to copy");
    }
  }, [code]);

  const copySnippet = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(snippet);
      showToast("success", "Registration code copied");
    } catch {
      showToast("error", "Failed to copy");
    }
  }, [snippet]);

  return (
    <div className="p-4 space-y-4 h-full overflow-auto">
      {/* Block Class */}
      <div>
        <div className="flex items-center justify-between mb-2">
          <div className="flex items-center gap-2">
            <FileCode size={13} className="text-orange-400" />
            <h3 className="text-[11px] font-medium text-stone-300">
              {toPascalCase(project.name)}.java
            </h3>
          </div>
          <button
            onClick={copyCode}
            className="flex items-center gap-1 px-2 py-1 rounded text-[10px] text-stone-500 hover:text-stone-300 bg-obsidian-800 hover:bg-obsidian-700 transition-colors"
          >
            <Copy size={11} />
            Copy
          </button>
        </div>
        <pre className="bg-obsidian-900 rounded-lg border border-obsidian-700 p-4 text-[11px] text-stone-300 font-mono overflow-x-auto leading-5 whitespace-pre">
          {code}
        </pre>
      </div>

      {/* Registration Snippet */}
      <div>
        <div className="flex items-center justify-between mb-2">
          <h3 className="text-[11px] font-medium text-stone-300">
            Registration Snippet
          </h3>
          <button
            onClick={copySnippet}
            className="flex items-center gap-1 px-2 py-1 rounded text-[10px] text-stone-500 hover:text-stone-300 bg-obsidian-800 hover:bg-obsidian-700 transition-colors"
          >
            <Copy size={11} />
            Copy
          </button>
        </div>
        <pre className="bg-obsidian-900 rounded-lg border border-obsidian-700 p-4 text-[11px] text-stone-300 font-mono overflow-x-auto leading-5 whitespace-pre">
          {snippet}
        </pre>
      </div>

      <p className="text-[10px] text-stone-600 text-center">
        This is a client-side preview. Click &quot;Export to Java&quot; in the toolbar to generate the actual files.
      </p>
    </div>
  );
}
